// Content for the portfolio UI kit — facts from the source repo (Yokai-2510/website-portfolio data.js), restructured.
window.ES_DATA = {
  identity: {
    name: 'Eshaan Sharma',
    role: 'Algorithmic trading & low-latency systems',
    location: 'Gurgaon, India',
    email: 'ethanarkham@gmail.com',
    github: 'https://github.com/Yokai-2510',
    linkedin: 'https://linkedin.com/in/eshaansharma2510',
  },
  hero: {
    status: 'Available for contract work · 2026',
    title: 'I build low-latency systems for real-time markets.',
    lede: 'Freelance algorithmic-trading developer. Event-driven order pipelines, market-data infrastructure, and the deterministic state machines that sit between signal and execution.',
  },
  proof: [
    { value: '<10', unit: 'ms', label: 'Internal hop latency, end to end', note: 'rank-displacement' },
    { value: '8', label: 'Independent engines over Redis Streams', note: 'rank-displacement' },
    { value: '<5', unit: 's', label: 'To flatten every broker position', note: 'kill switch' },
    { value: '3', unit: 'yrs', label: 'Production trading infrastructure', note: 'since 2023' },
  ],
  work: [
    { slug: 'rank-displacement', weight: 'lg', title: 'Rank-Displacement Options Trading System', domain: 'Trading', year: '2025', role: 'Architecture, build, live operations', status: 'Live',
      summary: 'Real-time options platform built around a 50ms leaderboard cycle across all Nifty 50 constituents.',
      body: 'Multi-process, event-driven architecture with eight independent engines coordinating exclusively over Redis Streams. Single source of truth for state, a deterministic order-execution flowchart, and a full 24×7 lifecycle with self-healing.',
      points: ['Eight engines, one transport: Redis Streams for fan-out, replay and consumer groups', 'Single-writer ownership of every key — state has exactly one author', 'Order execution modelled as an auditable flowchart, not an algorithm', 'Self-healing 24×7 lifecycle on AWS EC2 under systemd'],
      stack: ['Python 3.12', 'FastAPI', 'Redis Streams', 'PostgreSQL', 'TimescaleDB', 'Tauri', 'React', 'AWS EC2'],
      metric: { value: '50ms', label: 'leaderboard cycle' }, metrics: [{ value: '50', unit: 'ms', label: 'Leaderboard cycle' }, { value: '8', label: 'Engines' }, { value: '<10', unit: 'ms', label: 'Internal hop latency' }] },
    { slug: 'strategy-builder', weight: 'lg', title: 'Strategy Builder & Live Execution Platform', domain: 'Trading', year: '2024', role: 'Architecture, build', status: 'Delivered',
      summary: 'Management API, live engine and on-demand backtester — with bit-for-bit live/backtest parity.',
      body: 'Multi-process Python platform supporting parallel strategy evaluation across stocks and options sets. Hybrid storage: Mongo as source of truth for definitions and history, Redis as the high-speed state machine. Eleven indicators shared between live and backtest.',
      points: ['Three domains: management API, live trading engine, backtester', 'Mongo for definitions and history; Redis as the hot state machine', 'One indicator library shared by live and backtest — no drift'],
      stack: ['Python', 'FastAPI', 'Next.js', 'Redis', 'MongoDB Atlas', 'Multiprocessing'],
      metric: { value: '11', label: 'shared indicators' }, metrics: [{ value: '3', label: 'Domains' }, { value: '11', label: 'Shared indicators' }, { value: '1:1', label: 'Live / backtest parity' }] },
    { slug: 'option-chain', weight: 'md', title: 'Option Chain WebSocket Pipeline', domain: 'Engineering', year: '2023', role: 'Build', status: 'Delivered',
      summary: 'Reactive WebSocket pipeline with Protobuf decoding and dynamic strike subscription from live spot.',
      body: 'Live option-chain ingestion that subscribes and unsubscribes dynamically to hold ATM±N strikes, decoded via Protobuf and surfaced to Google Sheets in real time.',
      points: ['Dynamic subscribe/unsubscribe keeps ATM±N strikes in view', 'Protobuf decoding on the hot path', 'Real-time surface in Google Sheets'],
      stack: ['Python', 'Protobuf', 'WebSockets', 'Google Sheets API'], metric: { value: 'ATM±N', label: 'live strikes' }, metrics: [] },
    { slug: 'kill-switch', weight: 'md', title: 'Kotak Neo Automated Kill Switch', domain: 'Tools', year: '2024', role: 'Build', status: 'Delivered',
      summary: 'Desktop risk manager that auto-flattens broker positions in under five seconds.',
      body: 'Single-binary desktop tool where traders compose click-step sequences for their broker portal without touching code. Listens to Gmail for tripwires, then drives the portal via Playwright to flatten everything.',
      points: ['Traders compose portal click-sequences without code', 'Gmail tripwires trigger the flatten', 'Ships as a single PyInstaller binary'],
      stack: ['Python', 'CustomTkinter', 'Playwright', 'Gmail API', 'PyInstaller', 'SQLite'], metric: { value: '<5s', label: 'to flat' }, metrics: [] },
    { slug: 'signal-engine', weight: 'sm', title: 'Nifty 500 / F&O Signal Engine', domain: 'Trading', year: '2024', role: 'Build', status: 'Delivered',
      summary: 'Ten-point composite technical scanner across the Nifty 500 and F&O universe, with delivery-percentage logic.',
      body: 'Composite scoring across moving averages, momentum, volume and Bhavcopy delivery percentage. Nightly ingestion pipeline; a morning surface for actionable signals.',
      points: ['Ten-point composite score', 'Nightly Bhavcopy ingestion', 'Morning surface of actionable signals'],
      stack: ['Python', 'CustomTkinter', 'pandas-ta'], metric: { value: '10', label: 'point composite' }, metrics: [] },
    { slug: 'delivery-screener', weight: 'sm', title: 'NSE Delivery Analytics Screener', domain: 'Tools', year: '2023', role: 'Build', status: 'Delivered',
      summary: 'Fetches NSE delivery data on a schedule and surfaces rolling delivery statistics with live charts.',
      body: 'Pulls NSE delivery data on a schedule, computes rolling average, min and max delivery percentages, and pushes a live screener with charts to Google Sheets.',
      points: ['Scheduled NSE delivery ingestion', 'Rolling avg / min / max delivery %', 'Live charts in Google Sheets'],
      stack: ['Python', 'Google Sheets API', 'pandas'], metric: null, metrics: [] },
  ],
  writing: [
    { slug: 'single-writer', title: 'Single-writer ownership in Redis', kind: 'architecture', date: '2026.03', reading: '4 min', excerpt: 'If two processes can write to the same key, you’ve already lost. The discipline I use to keep ownership obvious across an eight-engine system.' },
    { slug: 'redis-streams', title: 'Redis Streams as a transport, not a queue', kind: 'architecture', date: '2026.02', reading: '6 min', excerpt: 'Streams give you fan-out, replay, and consumer groups in one primitive. Stop reaching for Kafka by reflex.' },
    { slug: 'ten-ms-budget', title: 'Spending a 10ms latency budget', kind: 'post-mortem', date: '2025.11', reading: '8 min', excerpt: 'A line-by-line walk through where the milliseconds actually go between tick and order submit.' },
    { slug: 'broker-ws', title: 'Stop polling broker portfolios', kind: 'field note', date: '2025.09', reading: '3 min', excerpt: 'If the broker exposes a portfolio WebSocket, the polling loop in your code is just bandwidth waste.' },
    { slug: 'deterministic-orders', title: 'Why order execution should be a flowchart', kind: 'architecture', date: '2025.07', reading: '5 min', excerpt: 'Replayable, testable, debuggable. A clever algorithm you can’t audit is worse than a boring one you can.' },
  ],
  lab: [
    { title: 'The Field', kind: 'experiment', note: 'The canvas behind this site — one system, two media.', seed: 'field' },
    { title: 'Ink studies', kind: 'experiment', note: 'Sketches for the Ink medium: diffusion, filaments, logograms.', seed: 'ink-studies' },
    { title: 'Hobby', kind: 'placeholder', empty: 'Drop an image', note: 'Space for interests outside the work.' },
    { title: 'Interest', kind: 'placeholder', empty: 'Drop an image', note: 'Reading, making, collecting — whatever belongs here.' },
  ],

  // Products: the systems people use day to day. User counts are illustrative — replace with real ones.
  products: [
    { name: 'Rank-Displacement Options System', tagline: 'Real-time options platform built around a 50ms leaderboard cycle across all Nifty 50 constituents.', status: 'Live', users: '14', usersLabel: 'trading desks', metric: { value: '50ms', label: 'leaderboard cycle' }, since: '2025', platform: ['Desktop', 'AWS'], seed: 'rank-displacement',
      description: 'Eight independent engines coordinating over Redis Streams, a deterministic order-execution flowchart, and a self-healing 24×7 lifecycle.', features: ['Eight engines, one transport', 'Single-writer state', 'Self-healing 24×7', 'Tauri desk app'] },
    { name: 'Strategy Builder', tagline: 'Build strategies, run them live, and backtest on demand — with bit-for-bit live/backtest parity.', status: 'In use', users: '230+', usersLabel: 'active users', metric: { value: '1:1', label: 'live / backtest parity' }, since: '2024', platform: ['Web', 'API'], seed: 'strategy-builder',
      description: 'A management API, a live trading engine and an on-demand backtester sharing one indicator library, so what you test is what runs.', features: ['Eleven shared indicators', 'Parallel evaluation', 'Mongo + Redis state'] },
    { name: 'Kill Switch for Kotak Neo', tagline: 'Desktop risk manager that flattens every broker position in under five seconds.', status: 'In use', users: '1,100+', usersLabel: 'installs', metric: { value: '<5s', label: 'to flat' }, since: '2024', platform: ['Desktop'], seed: 'kill-switch',
      description: 'Traders compose click-step sequences for their broker portal without code; Gmail tripwires trigger the flatten. Ships as a single binary.', features: ['No-code sequences', 'Gmail tripwires', 'Single binary'] },
  ],
  craft: {
    focus: [
      { title: 'Market-data ingestion', note: 'WebSocket and Protobuf pipelines that keep only what matters in view.' },
      { title: 'Signal computation', note: 'Composite scanners and one indicator library shared by live and backtest.' },
      { title: 'Deterministic order routing', note: 'Order execution as an auditable flowchart: replayable, testable, boring.' },
      { title: 'Observability', note: 'Prometheus, Grafana and OpenTelemetry on systems that run 24×7.' },
    ],
    credentials: [
      { year: '2022–25', title: 'Bachelor of Computer Applications (BCA)', issuer: 'IGNOU · distance programme, completed while freelancing full-time on production trading systems' },
      { year: '2024', title: 'Google Cloud Computing Foundations', issuer: 'Google Cloud Skills Boost' },
      { year: '2024', title: 'Problem Solving (Advanced)', issuer: 'HackerRank · data structures and algorithms' },
      { year: '2023', title: 'Scientific Computing with Python', issuer: 'freeCodeCamp' },
    ],
    experiments: [
      { title: 'The Field', kind: 'experiment', note: 'The canvas behind this site — one system, two media.', seed: 'field' },
      { title: 'Ink studies', kind: 'experiment', note: 'Smoke and release: two ways for ink to answer.', seed: 'ink-studies' },
    ],
  },
  aboutMe: {
    title: 'Who I am, beyond the systems.',
    intro: [
      'Freelance algorithmic trading and low-latency software developer. Three years of experience building production trading infrastructure for independent operators and small prop desks — architecture, deployment, and live operations.',
      'Comfortable owning systems end to end, from low-level networking to dashboards.',
      'Outside markets I explore everything — design, UI and UX, films, video games — and I believe it makes the engineering better. I am drawn to dystopias and cyberpunk, to Scandinavian culture, and to the mystique of the cosmos and the edges of what we can know. It shapes how I build: quiet on the surface, a great deal happening underneath.',
    ],
    principles: [
      { title: 'One writer per piece of state.', note: 'If two processes can write the same key, you have already lost. Ownership stays obvious.' },
      { title: 'Boring and auditable beats clever.', note: 'Replayable, testable, debuggable. I would rather ship a flowchart than a mystery.' },
      { title: 'Own it end to end.', note: 'Architecture, deployment and live operations — the pager included.' },
    ],
    interests: [
      { title: 'Design, UI & UX', kind: 'exploring', note: 'How things look, feel and behave — it makes the engineering better.', seed: 'design' },
      { title: 'Films & video games', kind: 'exploring', note: 'Dystopias and cyberpunk: worlds that ask what technology does to people.', seed: 'cyberpunk' },
      { title: 'The mystique', kind: 'reading', note: 'The cosmos, consciousness, and what we cannot yet measure.', seed: 'mystique' },
      { title: 'Scandinavian culture', kind: 'interest', note: 'Its myths, its restraint, its landscapes.', seed: 'nordic' },
      { title: 'Trekking', kind: 'hobby', note: 'Long walks up high, far from a screen.', seed: 'trekking' },
      { title: 'Cooking', kind: 'hobby', note: 'Another place where process and taste meet.', seed: 'cooking' },
    ],
    timeline: [
      { year: '2023', title: 'First production systems', note: 'Option-chain WebSocket pipeline and an NSE delivery screener.' },
      { year: '2024', title: 'Platforms and tools', note: 'Strategy builder with live/backtest parity, the Kotak Neo kill switch, the Nifty 500 signal engine.' },
      { year: '2025', title: 'Rank-displacement system', note: 'Eight engines over Redis Streams, live 24×7.' },
      { year: '2026', title: 'Writing, and taking new work', note: 'Available for contract and full-time engagements.' },
    ],
  },
  homeAbout: 'Based in Gurgaon, working anywhere. I own systems end to end — from low-level networking to dashboards.',
  about: [
    'Freelance algorithmic trading and low-latency software developer. Three years of experience building production trading infrastructure for independent operators and small prop desks — architecture, deployment, and live operations.',
    'Focus areas: market-data ingestion, signal computation, deterministic order routing, and observability. Comfortable owning systems end-to-end, from low-level networking to dashboards.',
    'Available for contract and full-time engagements. Time-zone flexible.',
  ],
  skills: [
    { group: 'Languages', items: ['Python', 'TypeScript', 'SQL', 'Rust (familiar)'] },
    { group: 'Markets', items: ['NSE/BSE equities', 'Options (F&O)', 'Order books', 'Market microstructure'] },
    { group: 'Backend', items: ['FastAPI', 'asyncio', 'uvloop', 'WebSockets', 'Protobuf'] },
    { group: 'Data', items: ['Redis Streams', 'PostgreSQL', 'TimescaleDB', 'MongoDB'] },
    { group: 'Ops', items: ['AWS EC2', 'systemd', 'Prometheus', 'Grafana', 'OpenTelemetry'] },
    { group: 'Frontend', items: ['React', 'Next.js', 'Tauri'] },
  ],
};
