// Portfolio data — single source of truth
window.PORTFOLIO = {
  identity: {
    name: "Eshaan Sharma",
    initials: "Es",
    role: "Algo Trading · Low-Latency Systems",
    location: "Gurgaon, India",
    timezone: "UTC+05:30",
    email: "ethanarkham@gmail.com",
    phone: "+91 93092 6729",
    github: "https://github.com/Yokai-2510",
    githubLabel: "github.com/Yokai-2510",
    linkedin: "https://linkedin.com/in/eshaansharma2510",
    linkedinLabel: "linkedin.com/in/eshaansharma2510",
    resume: "uploads/resume.docx",
  },

  hero: {
    intro: "Freelance algorithmic trading developer. I build low-latency Python systems for real-time markets — event-driven order pipelines, market-data infrastructure, and the deterministic state machines that sit between signal and execution.",
  },

  about: {
    paragraphs: [
      "Freelance algorithmic trading and low-latency software developer. Three years of experience building production trading infrastructure for independent operators and small prop desks — architecture, deployment, and live operations.",
      "Focus areas: market-data ingestion, signal computation, deterministic order routing, and observability. Comfortable owning systems end-to-end, from low-level networking to dashboards.",
      "Available for contract and full-time engagements. Time-zone flexible.",
    ],
  },

  skillIcons: [
    { name: "Python", svg: "python" },
    { name: "Redis", svg: "redis" },
    { name: "PostgreSQL", svg: "postgres" },
    { name: "FastAPI", svg: "fastapi" },
    { name: "AWS", svg: "aws" },
    { name: "Linux", svg: "linux" },
    { name: "Stock Market", svg: "stock" },
    { name: "React", svg: "react" },
  ],

  skills: [
    { group: "Languages", items: ["Python", "TypeScript", "JavaScript", "SQL", "Rust (familiar)"] },
    { group: "Markets", items: ["Stock Market", "Equities (NSE/BSE)", "Options (F&O)", "Index derivatives", "Order books", "Market microstructure", "Live tick data"] },
    { group: "Backend", items: ["FastAPI", "Uvicorn", "Pydantic", "asyncio", "uvloop", "Multiprocessing", "REST", "WebSockets", "Protobuf", "OAuth2 / JWT"] },
    { group: "Data Stores", items: ["Redis", "RedisJSON", "Redis Streams", "Pub/Sub", "Lua scripting", "PostgreSQL", "TimescaleDB", "MongoDB Atlas", "asyncpg", "pymongo"] },
    { group: "Systems Design", items: ["Event-driven pipelines", "Microservices", "Single-source-of-truth state", "Single-writer concurrency", "Crash recovery", "Low-latency design", "Multi-threading"] },
    { group: "Cloud & Ops", items: ["AWS EC2", "systemd", "Elastic IP", "Security Groups", "Linux (Ubuntu)", "SSH/SCP", "Git"] },
    { group: "Observability", items: ["Prometheus", "Grafana", "OpenTelemetry", "Loki", "Structured JSON logging"] },
    { group: "Frontend", items: ["React", "TypeScript", "Next.js", "Tauri", "Vite", "TailwindCSS"] },
    { group: "Data & Tooling", items: ["pandas", "NumPy", "pandas-ta", "Playwright", "PyInstaller", "PyOTP", "Google Sheets API"] },
  ],

  projects: [
    {
      slug: "rank-displacement",
      title: "Rank-Displacement Options Trading System",
      year: "2025",
      tagline: "Real-time options trading platform built around a 50ms leaderboard cycle across all Nifty 50 constituents.",
      description: "Multi-process, event-driven architecture with eight independent engines coordinating exclusively over Redis Streams. Single source of truth for state, deterministic order-execution flowchart, full 24×7 lifecycle with self-healing. Internal hop latency consistently under the 10ms budget end-to-end.",
      stack: ["Python 3.12", "FastAPI", "Redis Streams", "PostgreSQL", "TimescaleDB", "Tauri", "React", "AWS EC2"],
      links: { github: "https://github.com/Yokai-2510", demo: "#", site: "#" },
      thumb: "rd",
    },
    {
      slug: "strategy-builder",
      title: "Strategy Builder & Live Execution Platform",
      year: "2024",
      tagline: "Three-domain system — management API, live trading engine, on-demand backtester — with bit-for-bit live/backtest parity.",
      description: "Multi-process Python platform supporting parallel strategy evaluation across stocks and options sets. Hybrid storage: Mongo as source-of-truth for definitions and history, Redis as the high-speed state machine. 11 indicators shared between live and backtest.",
      stack: ["Python", "FastAPI", "Next.js", "Redis", "MongoDB Atlas", "Multiprocessing"],
      links: { github: "https://github.com/Yokai-2510/Amish-Trading-Setup", demo: "#", site: "#" },
      thumb: "sb",
    },
    {
      slug: "kill-switch",
      title: "Kotak Neo Automated Kill Switch",
      year: "2024",
      tagline: "Desktop risk manager that auto-flattens broker positions in under 5 seconds via configurable browser automation.",
      description: "Single-binary desktop tool where traders compose click-step sequences for their broker portal without touching code. Listens to Gmail for tripwires, then drives the broker portal via Playwright to flatten everything.",
      stack: ["Python", "CustomTkinter", "Playwright", "Gmail API", "PyInstaller", "SQLite"],
      links: { github: "https://github.com/Yokai-2510", demo: "#", site: "#" },
      thumb: "ks",
    },
    {
      slug: "signal-engine",
      title: "Nifty 500 / F&O Signal Engine",
      year: "2024",
      tagline: "10-point composite technical scanner across Nifty 500 + F&O universe, with delivery-percentage logic on top.",
      description: "Composite scoring across moving averages, momentum, volume, and Bhavcopy delivery percentage. Nightly ingestion pipeline; morning surface for actionable signals.",
      stack: ["Python", "CustomTkinter", "pandas-ta"],
      links: { github: "https://github.com/Yokai-2510", demo: "#", site: "#" },
      thumb: "se",
    },
    {
      slug: "option-chain",
      title: "Option Chain WebSocket Pipeline",
      year: "2023",
      tagline: "Reactive WebSocket V3 pipeline with Protobuf decoding and dynamic strike subscription based on live spot.",
      description: "Live option chain ingestion, dynamic subscribe/unsubscribe to maintain ATM±N strikes, decoded via Protobuf and surfaced to Google Sheets in real time.",
      stack: ["Python", "Protobuf", "WebSockets", "Google Sheets API"],
      links: { github: "https://github.com/Yokai-2510", demo: "#", site: "#" },
      thumb: "oc",
    },
    {
      slug: "delivery-screener",
      title: "NSE Delivery Analytics Screener",
      year: "2023",
      tagline: "Auto-fetches NSE delivery data, computes avg/min/max delivery percentages, surfaces live charts.",
      description: "Pulls NSE delivery data on a schedule, computes rolling delivery statistics, and pushes a live screener with charts to Google Sheets.",
      stack: ["Python", "Google Sheets API", "pandas"],
      links: { github: "https://github.com/Yokai-2510", demo: "#", site: "#" },
      thumb: "ds",
    },
  ],

  notes: [
    {
      slug: "single-writer",
      title: "Single-writer ownership in Redis",
      kind: "architecture",
      date: "2026.03",
      excerpt: "If two processes can write to the same key, you've already lost. The discipline I use to keep ownership obvious across an eight-engine system.",
      reading: "4 min",
    },
    {
      slug: "redis-streams",
      title: "Redis Streams as a transport, not a queue",
      kind: "architecture",
      date: "2026.02",
      excerpt: "Streams give you fan-out, replay, and consumer groups in one primitive. Stop reaching for Kafka by reflex.",
      reading: "6 min",
    },
    {
      slug: "ten-ms-budget",
      title: "Spending a 10ms latency budget",
      kind: "post-mortem",
      date: "2025.11",
      excerpt: "A line-by-line walk through where the milliseconds actually go between tick and order submit.",
      reading: "8 min",
    },
    {
      slug: "broker-ws",
      title: "Stop polling broker portfolios",
      kind: "field note",
      date: "2025.09",
      excerpt: "If the broker exposes a portfolio WebSocket, the polling loop in your code is just bandwidth waste.",
      reading: "3 min",
    },
    {
      slug: "deterministic-orders",
      title: "Why order execution should be a flowchart",
      kind: "architecture",
      date: "2025.07",
      excerpt: "Replayable, testable, debuggable. A clever algorithm you can't audit is worse than a boring one you can.",
      reading: "5 min",
    },
  ],
};
